2015/08/24 22:58:55 [error] 12569#0: *9 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 22:58:56 [error] 12569#0: *10 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 22:59:51 [error] 12569#0: *11 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 22:59:51 [error] 12569#0: *12 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:00:03 [error] 12569#0: *13 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:00:04 [error] 12569#0: *14 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:00:05 [error] 12569#0: *15 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:00:05 [error] 12569#0: *16 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:00:06 [error] 12569#0: *17 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:00:06 [error] 12569#0: *18 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:01:26 [error] 12569#0: *19 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:01:27 [error] 12569#0: *20 lua entry thread aborted: runtime error: ./pub/index.lua:8: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:01:43 [error] 12569#0: *22 lua entry thread aborted: runtime error: ./pub/index.lua:9: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:01:44 [error] 12569#0: *23 lua entry thread aborted: runtime error: ./pub/index.lua:9: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:02:03 [error] 12569#0: *24 lua entry thread aborted: runtime error: ./pub/index.lua:9: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:02:03 [error] 12569#0: *25 lua entry thread aborted: runtime error: ./pub/index.lua:9: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:02:26 [error] 12569#0: *26 lua entry thread aborted: runtime error: ./pub/index.lua:10: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:02:27 [error] 12569#0: *27 lua entry thread aborted: runtime error: ./pub/index.lua:10: attempt to call field 'run' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
2015/08/24 23:04:56 [error] 12569#0: *28 lua entry thread aborted: runtime error: ./pub/index.lua:10: bad argument #1 to 'say' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:04:56 [error] 12569#0: *31 lua entry thread aborted: runtime error: ./pub/index.lua:10: bad argument #1 to 'say' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:04:56 [error] 12569#0: *32 lua entry thread aborted: runtime error: ./pub/index.lua:10: bad argument #1 to 'say' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:04:56 [error] 12569#0: *33 lua entry thread aborted: runtime error: ./pub/index.lua:10: bad argument #1 to 'say' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:05:01 [error] 12569#0: *34 lua entry thread aborted: runtime error: ./pub/index.lua:10: bad argument #1 to 'say' (non-array table found)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:07 [error] 12569#0: *35 lua entry thread aborted: runtime error: ./pub/index.lua:31: attempt to call field 'print_r' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:07 [error] 12569#0: *36 lua entry thread aborted: runtime error: ./pub/index.lua:31: attempt to call field 'print_r' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:07 [error] 12569#0: *37 lua entry thread aborted: runtime error: ./pub/index.lua:31: attempt to call field 'print_r' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:07 [error] 12569#0: *38 lua entry thread aborted: runtime error: ./pub/index.lua:31: attempt to call field 'print_r' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:12 [error] 12569#0: *39 lua entry thread aborted: runtime error: ./pub/index.lua:31: attempt to call field 'print_r' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:21 [error] 12569#0: *40 lua entry thread aborted: runtime error: ./pub/index.lua:21: attempt to call global 'srep' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:21 [error] 12569#0: *41 lua entry thread aborted: runtime error: ./pub/index.lua:21: attempt to call global 'srep' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:32 [error] 12569#0: *42 lua entry thread aborted: runtime error: ./pub/index.lua:14: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:32 [error] 12569#0: *43 lua entry thread aborted: runtime error: ./pub/index.lua:14: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:33 [error] 12569#0: *44 lua entry thread aborted: runtime error: ./pub/index.lua:14: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:06:33 [error] 12569#0: *45 lua entry thread aborted: runtime error: ./pub/index.lua:14: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:07:03 [error] 12569#0: *46 lua entry thread aborted: runtime error: ./pub/index.lua:14: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:09:05 [error] 12569#0: *47 lua entry thread aborted: runtime error: ./pub/index.lua:1: module 'vanilla.v.libs.utils' not found:
	no field package.preload['vanilla.v.libs.utils']
	no file './vanilla/v/libs/utils.lua'
	no file './lib/vanilla/v/libs/utils.lua'
	no file '/Users/zhoujing/.luarocks/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/Users/zhoujing/.luarocks/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/luarocks-2.2.2/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/luarocks-2.2.2/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/luajit/share/luajit-2.1.0-alpha/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/nginx_x/luajit/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/luajit/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.so'
	no file './lib/vanilla/v/libs/utils.so'
	no file '/Users/zhoujing/.luarocks/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/luarocks-2.2.2/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file './vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils.so'
	no file './vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/nginx_x/luajit/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vanilla.so'
	no file './lib/vanilla.so'
	no file '/Users/zhoujing/.luarocks/lib/lua/5.1/vanilla.so'
	no file '/usr/local/luarocks-2.2.2/lib/lua/5.1/vanilla.so'
	no file './vanilla.so'
	no file '/usr/local/lib/lua/5.1/vanilla.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/nginx_x/lualib/vanilla.so'
	no file './vanilla.so'
	no file '/usr/local/lib/lua/5.1/vanilla.so'
	no file '/usr/local/nginx_x/luajit/lib/lua/5.1/vanilla.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/24 23:09:06 [error] 12569#0: *49 lua entry thread aborted: runtime error: ./pub/index.lua:1: module 'vanilla.v.libs.utils' not found:
	no field package.preload['vanilla.v.libs.utils']
	no file './vanilla/v/libs/utils.lua'
	no file './lib/vanilla/v/libs/utils.lua'
	no file '/Users/zhoujing/.luarocks/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/Users/zhoujing/.luarocks/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/luarocks-2.2.2/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/luarocks-2.2.2/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/luajit/share/luajit-2.1.0-alpha/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file '/usr/local/nginx_x/luajit/share/lua/5.1/vanilla/v/libs/utils.lua'
	no file '/usr/local/nginx_x/luajit/share/lua/5.1/vanilla/v/libs/utils/init.lua'
	no file './vanilla/v/libs/utils.so'
	no file './lib/vanilla/v/libs/utils.so'
	no file '/Users/zhoujing/.luarocks/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/luarocks-2.2.2/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file './vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/nginx_x/lualib/vanilla/v/libs/utils.so'
	no file './vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/nginx_x/luajit/lib/lua/5.1/vanilla/v/libs/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vanilla.so'
	no file './lib/vanilla.so'
	no file '/Users/zhoujing/.luarocks/lib/lua/5.1/vanilla.so'
	no file '/usr/local/luarocks-2.2.2/lib/lua/5.1/vanilla.so'
	no file './vanilla.so'
	no file '/usr/local/lib/lua/5.1/vanilla.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/nginx_x/lualib/vanilla.so'
	no file './vanilla.so'
	no file '/usr/local/lib/lua/5.1/vanilla.so'
	no file '/usr/local/nginx_x/luajit/lib/lua/5.1/vanilla.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):1: in function <content_by_lua(nginx.conf:34):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
